import type { CSSProperties } from "react";

export const token = {
    bg: "#070d1a",
    surface: "#0d1524",
    border: "rgba(255,255,255,0.08)",
    text: "#e2e8f0",
    textMuted: "#64748b",
    textDim: "#94a3b8",
    radius: 16,
    radiusSm: 10,
    font: "'DM Mono', 'Fira Code', monospace",
    fontDisplay: "'Syne', 'Montserrat', sans-serif",
} as const;

export const styles: Record<string, CSSProperties> = {
    root: {
        minHeight: "100vh",
        background: token.bg,
        color: token.text,
        fontFamily: token.font,
        position: "relative",
        overflowX: "hidden",
    },
    bgGrid: {
        position: "fixed",
        inset: 0,
        backgroundImage: `
      linear-gradient(rgba(255,255,255,0.025) 1px, transparent 1px),
      linear-gradient(90deg, rgba(255,255,255,0.025) 1px, transparent 1px)
    `,
        backgroundSize: "48px 48px",
        pointerEvents: "none",
        zIndex: 0,
    },

    // Topbar
    topbar: {
        position: "sticky",
        top: 0,
        zIndex: 100,
        display: "flex",
        alignItems: "center",
        justifyContent: "space-between",
        padding: "14px 32px",
        background: "rgba(7,13,26,0.85)",
        backdropFilter: "blur(16px)",
        borderBottom: `1px solid ${token.border}`,
    },
    topbarLeft: { display: "flex", alignItems: "center", gap: 20 },
    topbarRight: { display: "flex", gap: 10 },
    logo: {
        fontFamily: token.fontDisplay,
        fontWeight: 700,
        fontSize: 18,
        letterSpacing: "-0.5px",
        display: "flex",
        alignItems: "center",
        gap: 8,
    },
    logoDot: {
        width: 10,
        height: 10,
        borderRadius: "50%",
        background: "#3b82f6",
        boxShadow: "0 0 10px #3b82f6aa",
        display: "inline-block",
    },
    logoSub: { color: token.textMuted, fontWeight: 400 },
    widgetCount: {
        fontSize: 12,
        color: token.textMuted,
        background: "rgba(255,255,255,0.05)",
        padding: "4px 10px",
        borderRadius: 20,
        border: `1px solid ${token.border}`,
    },
    btnPrimary: {
        background: "#3b82f6",
        color: "#fff",
        border: "none",
        borderRadius: token.radiusSm,
        padding: "8px 18px",
        fontSize: 13,
        fontFamily: token.font,
        cursor: "pointer",
        fontWeight: 600,
        letterSpacing: "0.3px",
    },
    btnOutline: {
        background: "transparent",
        color: token.textDim,
        border: `1px solid ${token.border}`,
        borderRadius: token.radiusSm,
        padding: "8px 16px",
        fontSize: 13,
        fontFamily: token.font,
        cursor: "pointer",
    },

    // Grid
    main: {
        position: "relative",
        zIndex: 1,
        padding: "28px 32px",
    },
    grid: {
        display: "grid",
        gridTemplateColumns: "repeat(auto-fill, minmax(320px, 1fr))",
        gap: 20,
        width: "100%",
    },
    empty: { textAlign: "center", paddingTop: 120 },

    // Widget shell
    widgetShell: {
        background: token.surface,
        border: `1px solid ${token.border}`,
        borderRadius: token.radius,
        overflow: "hidden",
        cursor: "grab",
        transition: "all 0.2s ease",
        boxShadow: "0 4px 24px rgba(0,0,0,0.3)",
        display: "flex",
        flexDirection: "column",
    },
    widgetHeader: {
        display: "flex",
        alignItems: "center",
        justifyContent: "space-between",
        padding: "12px 16px",
        borderBottom: `1px solid ${token.border}`,
        background: "rgba(255,255,255,0.02)",
    },
    widgetHeaderLeft: { display: "flex", alignItems: "center", gap: 8 },
    widgetAccent: { width: 4, height: 14, borderRadius: 2, display: "inline-block" },
    widgetLabel: { fontSize: 12, color: token.textDim, letterSpacing: "0.5px", fontWeight: 500 },
    widgetActions: { display: "flex", alignItems: "center", gap: 8 },
    dragHandle: { color: token.textMuted, fontSize: 14, cursor: "grab", userSelect: "none", letterSpacing: 1 },
    removeBtn: {
        background: "transparent",
        border: "none",
        color: token.textMuted,
        fontSize: 18,
        cursor: "pointer",
        lineHeight: 1,
        padding: "0 2px",
        borderRadius: 4,
    },
    widgetBody: {
        padding: "16px",
        display: "flex",
        flexDirection: "column",
        justifyContent: "center",
        flex: 1,
    },

    // Clock
    clockWidget: { textAlign: "center", padding: "8px 0" },
    clockTime: {
        fontFamily: token.fontDisplay,
        fontSize: 42,
        fontWeight: 700,
        letterSpacing: "-2px",
        color: "#f1f5f9",
    },
    clockColon: { color: "#3b82f6" },
    clockSeconds: { fontSize: 26, color: token.textMuted },
    clockDate: { fontSize: 12, color: token.textMuted, marginTop: 6 },

    // Weather
    weatherWidget: { display: "flex", flexDirection: "column", gap: 12 },
    weatherTop: { display: "flex", justifyContent: "space-between", alignItems: "flex-start" },
    weatherCity: { fontSize: 15, fontWeight: 600, color: "#e2e8f0" },
    weatherCondition: { fontSize: 12, color: token.textMuted, marginTop: 2 },
    weatherTempBlock: { display: "flex", alignItems: "center", gap: 6 },
    weatherIcon: { fontSize: 28 },
    weatherTemp: { fontSize: 32, fontWeight: 700, color: "#fbbf24" },
    weatherMeta: {
        display: "flex",
        gap: 14,
        fontSize: 12,
        color: token.textDim,
        background: "rgba(255,255,255,0.03)",
        borderRadius: 8,
        padding: "8px 12px",
    },
    weatherForecast: { display: "flex", justifyContent: "space-between" },
    forecastItem: { textAlign: "center", fontSize: 12 },
    forecastDay: { color: token.textMuted, marginBottom: 4 },
    forecastTemps: { marginTop: 4, fontSize: 11 },

    // Counter
    counterWidget: {
        textAlign: "center",
        padding: "8px 0",
        border: "1px solid",
        borderRadius: 10,
        background: "rgba(255,255,255,0.02)",
    },
    counterValue: {
        fontFamily: token.fontDisplay,
        fontSize: 36,
        fontWeight: 700,
        letterSpacing: "-1px",
        margin: "8px 0 4px",
    },
    counterLabel: { fontSize: 12, color: token.textMuted },

    // Stats
    statsWidget: { display: "flex", flexDirection: "column", gap: 10 },
    statRow: { display: "flex", alignItems: "center", justifyContent: "space-between" },
    statLabel: { fontSize: 11, color: token.textMuted, marginBottom: 4 },
    statValue: { fontSize: 22, fontWeight: 700 },
    statDivider: { height: 1, background: token.border },

    // Quote
    quoteWidget: { position: "relative", paddingTop: 4 },
    quoteText: { fontSize: 15, lineHeight: 1.7, color: "#cbd5e1", position: "relative", zIndex: 1, minHeight: 44 },
    quoteAuthor: { fontSize: 11, color: "#3b82f6", marginTop: 8 },
    quoteBtn: {
        background: "none",
        border: "none",
        color: token.textMuted,
        fontSize: 11,
        cursor: "pointer",
        padding: 0,
        marginTop: 8,
        fontFamily: token.font,
    },

    // Activity
    activityWidget: { display: "flex", flexDirection: "column", gap: 0 },
    activityTitle: { fontSize: 11, color: token.textMuted, marginBottom: 10, letterSpacing: 1, textTransform: "uppercase" },
    activityList: { display: "flex", flexDirection: "column", gap: 12 },
    activityItem: { display: "flex", gap: 10, alignItems: "flex-start" },
    activityDot: {
        width: 28,
        height: 28,
        borderRadius: "50%",
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        fontSize: 13,
        flexShrink: 0,
        opacity: 0.85,
    },
    activityContent: {},
    activityText: { fontSize: 12, color: "#cbd5e1" },
    activityTime: { fontSize: 11, color: token.textMuted, marginTop: 2 },

    // Panel
    overlay: {
        position: "fixed",
        inset: 0,
        background: "rgba(0,0,0,0.5)",
        zIndex: 200,
        backdropFilter: "blur(4px)",
    },
    panel: {
        position: "fixed",
        top: 0,
        right: 0,
        width: 320,
        height: "100vh",
        background: token.surface,
        borderLeft: `1px solid ${token.border}`,
        zIndex: 201,
        display: "flex",
        flexDirection: "column",
        boxShadow: "-20px 0 60px rgba(0,0,0,0.5)",
    },
    panelHeader: {
        display: "flex",
        alignItems: "center",
        justifyContent: "space-between",
        padding: "20px 24px",
        borderBottom: `1px solid ${token.border}`,
    },
    panelTitle: { fontSize: 16, fontWeight: 600, fontFamily: token.fontDisplay },
    panelClose: { background: "none", border: "none", color: token.textMuted, fontSize: 22, cursor: "pointer" },
    panelBody: { padding: "16px", overflowY: "auto", display: "flex", flexDirection: "column", gap: 10 },
    panelItem: {
        display: "flex",
        alignItems: "center",
        gap: 14,
        padding: "14px",
        borderRadius: token.radiusSm,
        border: `1px solid rgba(255,255,255,0.08)`,
        background: "rgba(255,255,255,0.02)",
        cursor: "pointer",
        transition: "all 0.15s",
    },
    panelItemIcon: { width: 40, height: 40, borderRadius: 10, display: "flex", alignItems: "center", justifyContent: "center", fontSize: 20, flexShrink: 0 },
    panelItemLabel: { fontSize: 13, fontWeight: 600, color: "#e2e8f0" },
    panelItemDesc: { fontSize: 11, color: token.textMuted, marginTop: 2 },
};